// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNsa_lLa_L35-iSA1J8NxO8xMWJJaw810',
    appId: '1:1009599680655:web:24adb32d7f5febc23fe0fa',
    messagingSenderId: '1009599680655',
    projectId: 'graduation-project-3fd49',
    authDomain: 'graduation-project-3fd49.firebaseapp.com',
    storageBucket: 'graduation-project-3fd49.appspot.com',
    measurementId: 'G-4K1G5SSSVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn5j66LqXPJ9cUnz4im5qygNdk__SWXdc',
    appId: '1:1009599680655:android:66a35be4d5148c0f3fe0fa',
    messagingSenderId: '1009599680655',
    projectId: 'graduation-project-3fd49',
    storageBucket: 'graduation-project-3fd49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGaqtLUwhUUzx5ZxsOTVEfuHxnyIOosSI',
    appId: '1:1009599680655:ios:dc1c51003da8d4d63fe0fa',
    messagingSenderId: '1009599680655',
    projectId: 'graduation-project-3fd49',
    storageBucket: 'graduation-project-3fd49.appspot.com',
    iosBundleId: 'com.example.ourProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGaqtLUwhUUzx5ZxsOTVEfuHxnyIOosSI',
    appId: '1:1009599680655:ios:559d975288fe25643fe0fa',
    messagingSenderId: '1009599680655',
    projectId: 'graduation-project-3fd49',
    storageBucket: 'graduation-project-3fd49.appspot.com',
    iosBundleId: 'com.example.ourProject1.RunnerTests',
  );
}
